name: migrate
on:
  push:
    branches: [main]
    paths:
      - "sql/**.sql"
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply SQL migrations
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          for f in $(ls -1 sql/*.sql | sort); do
            echo "Applying $f"
            psql "$SUPABASE_DB_URL" -v "ON_ERROR_STOP=1" -f "$f"
          done
